# Generated by Django 5.1.7 on 2025-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('amenities', models.JSONField(default=list)),
                ('image_urls', models.JSONField(default=list)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
