# Generated by Django 5.1.7 on 2025-05-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_owner_and_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_owner_i_401b51_idx',
            old_name='listings_listing_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_status_29a9da_idx',
            old_name='listings_listing_status_created_idx',
        ),
    ]
