# Generated by Django 5.1.7 on 2025-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_id', models.IntegerField()),
                ('user', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apps_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
